version: '3.8'

services:
  news_api:
    build:
      context: .
    container_name: news_api
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=docker
      - ENABLE_SYNC=false  # Ensure syncToElastic.js doesn't run
    depends_on:
      - elasticsearch  # Optional, only if running ES here
